default_language_version:
  python: python3.8

default_install_hook_types: [pre-commit, commit-msg]
default_stages: [commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: end-of-file-fixer
      - id: file-contents-sorter
        files: '^.wordlist.txt$'
        args: [--unique]
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.10.0
    hooks:
      - id: markdownlint-cli2

  - repo: https://github.com/StreamHPC/rocm-docs-spellcheck
    rev: v0.1.0
    hooks:
      - id: spellcheck-markdown
        exclude: "^tests/|^(CHANGELOG|README).md$"

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: just mypy
        types_or: [python, pyi]
        language: system
        exclude: ^docs/|^tests/(sites|templates)
      - id: ruff
        name: ruff
        entry: just ruff
        types_or: [python, pyi]
        language: system
        exclude: ^docs/|^tests/(sites|templates)
        require_serial: true
      - id: isort
        name: isort
        entry: just isort
        types_or: [python, pyi]
        language: system
      - id: format
        name: format
        entry: just format
        types_or: [python, pyi]
        language: system
      - id: commitizen
        name: commitizen
        entry: just _check-commit-mesg
        stages: [commit-msg]
        language: system
      - id: pip-compile
        name: pip-compile
        entry: just lock-deps
        files: ^pyproject.toml|requirements.txt$
        pass_filenames: false
        language: system
