name: Code Linting
on:
  pull_request:

jobs:
  lint:
    name: Python
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        python-version: ["3.8"]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3.5.0
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "${{ matrix.python-version }}"
        cache: pip
        cache-dependency-path: |
          pyproject.toml
          requirements.txt
    - name: Cache venv
      uses: actions/cache@v3.3.1
      with:
        path: .venv
        key: venv-${{ matrix.os }}-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml','requirements.txt') }}
    - run: echo "PRE_COMMIT_HOME=$Env:GITHUB_WORKSPACE/.cache/pre-commit" >> "$Env:GITHUB_ENV"
      if: ${{ startsWith(matrix.os, 'windows') }}
    - run: echo "PRE_COMMIT_HOME=$GITHUB_WORKSPACE/.cache/pre-commit" >> "$GITHUB_ENV"
      if: ${{ !startsWith(matrix.os, 'windows') }}
    - name: Cache pre-commit
      uses: actions/cache@v3.3.1
      with:
        path: ${{ env.PRE_COMMIT_HOME }}
        key: pre-commit-${{ matrix.os }}-${{ matrix.python-version }}-${{ hashFiles('.pre-commit-config.yaml') }}
    - name: Install just
      uses: extractions/setup-just@v1
      with:
        just-version: '1.13.0'
    - name: Create virtual env, install requirements
      run: just deps
    - name: Check commit messages
      run: just _check-commit-range "refs/remotes/origin/${{ github.base_ref }}..HEAD"
    - name: Check linting, formatting, types
      run: just check-codestyle
